services:
  db:
    container_name: EventConnect
    image: postgres:16.1-alpine
    env_file:
      - .env
    ports:
      - "4232:5432"
    volumes:
      - /Users/almazmasagutov/EventConnect:/var/lib/postgresql/data